/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '@angular/http/src/http_module';
import * as import7 from '@angular/forms/src/directives';
import * as import8 from '@angular/forms/src/form_providers';
import * as import9 from './messages/message.module';
import * as import10 from './auth/auth.module';
import * as import11 from '@angular/common/src/localization';
import * as import12 from '@angular/core/src/application_init';
import * as import13 from '@angular/core/src/testability/testability';
import * as import14 from '@angular/core/src/application_ref';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import17 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import18 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import19 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import20 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import21 from '@angular/core/src/linker/view_utils';
import * as import22 from '@angular/platform-browser/src/browser/title';
import * as import23 from '@angular/http/src/backends/browser_xhr';
import * as import24 from '@angular/http/src/base_response_options';
import * as import25 from '@angular/http/src/backends/xhr_backend';
import * as import26 from '@angular/http/src/base_request_options';
import * as import27 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import28 from './errors/error.service';
import * as import29 from './messages/message.service';
import * as import30 from '@angular/forms/src/form_builder';
import * as import31 from '@angular/common/src/location/location';
import * as import32 from '@angular/router/src/url_tree';
import * as import33 from '@angular/router/src/router_outlet_map';
import * as import34 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import35 from './auth/auth.service';
import * as import36 from '@angular/core/src/di/injector';
import * as import37 from './auth/signup.component.ngfactory';
import * as import38 from './auth/signin.component.ngfactory';
import * as import39 from './auth/logout.component.ngfactory';
import * as import40 from './messages/messages.component.ngfactory';
import * as import41 from './auth/authentication.component.ngfactory';
import * as import42 from './app.component.ngfactory';
import * as import43 from '@angular/core/src/application_tokens';
import * as import44 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import45 from '@angular/platform-browser/src/dom/events/key_events';
import * as import46 from '@angular/core/src/zone/ng_zone';
import * as import47 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import48 from './auth/signup.component';
import * as import49 from './auth/signin.component';
import * as import50 from './auth/logout.component';
import * as import51 from './messages/messages.component';
import * as import52 from './auth/authentication.component';
import * as import53 from '@angular/common/src/location/platform_location';
import * as import54 from '@angular/common/src/location/location_strategy';
import * as import55 from '@angular/router/src/router';
import * as import56 from '@angular/core/src/console';
import * as import57 from '@angular/core/src/i18n/tokens';
import * as import58 from '@angular/core/src/error_handler';
import * as import59 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import60 from '@angular/platform-browser/src/dom/animation_driver';
import * as import61 from '@angular/core/src/render/api';
import * as import62 from '@angular/core/src/security';
import * as import63 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import64 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import65 from '@angular/http/src/interfaces';
import * as import66 from '@angular/http/src/http';
import * as import67 from '@angular/router/src/router_config_loader';
import * as import68 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import69 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _HttpModule_5:import6.HttpModule;
  _InternalFormsSharedModule_6:import7.InternalFormsSharedModule;
  _FormsModule_7:import8.FormsModule;
  _MessageModule_8:import9.MessageModule;
  _ReactiveFormsModule_9:import8.ReactiveFormsModule;
  _AuthModule_10:import10.AuthModule;
  _AppModule_11:import1.AppModule;
  __LOCALE_ID_12:any;
  __NgLocalization_13:import11.NgLocaleLocalization;
  _ErrorHandler_14:any;
  _ApplicationInitStatus_15:import12.ApplicationInitStatus;
  _Testability_16:import13.Testability;
  _ApplicationRef__17:import14.ApplicationRef_;
  __ApplicationRef_18:any;
  __Compiler_19:import15.Compiler;
  __APP_ID_20:any;
  __DOCUMENT_21:any;
  __HAMMER_GESTURE_CONFIG_22:import16.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_23:any[];
  __EventManager_24:import17.EventManager;
  __DomSharedStylesHost_25:import18.DomSharedStylesHost;
  __AnimationDriver_26:any;
  __DomRootRenderer_27:import19.DomRootRenderer_;
  __RootRenderer_28:any;
  __DomSanitizer_29:import20.DomSanitizerImpl;
  __Sanitizer_30:any;
  __ViewUtils_31:import21.ViewUtils;
  __IterableDiffers_32:any;
  __KeyValueDiffers_33:any;
  __SharedStylesHost_34:any;
  __Title_35:import22.Title;
  __BrowserXhr_36:import23.BrowserXhr;
  __ResponseOptions_37:import24.BaseResponseOptions;
  __XSRFStrategy_38:any;
  __XHRBackend_39:import25.XHRBackend;
  __RequestOptions_40:import26.BaseRequestOptions;
  __Http_41:any;
  __RadioControlRegistry_42:import27.RadioControlRegistry;
  __ErrorService_43:import28.ErrorService;
  __MessageService_44:import29.MessageService;
  __FormBuilder_45:import30.FormBuilder;
  __ROUTES_46:any[];
  __ROUTER_CONFIGURATION_47:any;
  __LocationStrategy_48:any;
  __Location_49:import31.Location;
  __UrlSerializer_50:import32.DefaultUrlSerializer;
  __RouterOutletMap_51:import33.RouterOutletMap;
  __NgModuleFactoryLoader_52:import34.SystemJsNgModuleLoader;
  __Router_53:any;
  __ActivatedRoute_54:any;
  __APP_BOOTSTRAP_LISTENER_55:any[];
  __AuthService_56:import35.AuthService;
  constructor(parent:import36.Injector) {
    super(parent,[
      import37.SignupComponentNgFactory,
      import38.SigninComponentNgFactory,
      import39.LogoutComponentNgFactory,
      import40.MessagesComponentNgFactory,
      import41.AuthenticationComponentNgFactory,
      import42.AppComponentNgFactory
    ]
    ,[import42.AppComponentNgFactory]);
  }
  get _LOCALE_ID_12():any {
    if ((this.__LOCALE_ID_12 == (null as any))) { (this.__LOCALE_ID_12 = 'en-US'); }
    return this.__LOCALE_ID_12;
  }
  get _NgLocalization_13():import11.NgLocaleLocalization {
    if ((this.__NgLocalization_13 == (null as any))) { (this.__NgLocalization_13 = new import11.NgLocaleLocalization(this._LOCALE_ID_12)); }
    return this.__NgLocalization_13;
  }
  get _ApplicationRef_18():any {
    if ((this.__ApplicationRef_18 == (null as any))) { (this.__ApplicationRef_18 = this._ApplicationRef__17); }
    return this.__ApplicationRef_18;
  }
  get _Compiler_19():import15.Compiler {
    if ((this.__Compiler_19 == (null as any))) { (this.__Compiler_19 = new import15.Compiler()); }
    return this.__Compiler_19;
  }
  get _APP_ID_20():any {
    if ((this.__APP_ID_20 == (null as any))) { (this.__APP_ID_20 = import43._appIdRandomProviderFactory()); }
    return this.__APP_ID_20;
  }
  get _DOCUMENT_21():any {
    if ((this.__DOCUMENT_21 == (null as any))) { (this.__DOCUMENT_21 = import4._document()); }
    return this.__DOCUMENT_21;
  }
  get _HAMMER_GESTURE_CONFIG_22():import16.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_22 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_22 = new import16.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_22;
  }
  get _EVENT_MANAGER_PLUGINS_23():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_23 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_23 = [
      new import44.DomEventsPlugin(),
      new import45.KeyEventsPlugin(),
      new import16.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_22)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_23;
  }
  get _EventManager_24():import17.EventManager {
    if ((this.__EventManager_24 == (null as any))) { (this.__EventManager_24 = new import17.EventManager(this._EVENT_MANAGER_PLUGINS_23,this.parent.get(import46.NgZone))); }
    return this.__EventManager_24;
  }
  get _DomSharedStylesHost_25():import18.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_25 == (null as any))) { (this.__DomSharedStylesHost_25 = new import18.DomSharedStylesHost(this._DOCUMENT_21)); }
    return this.__DomSharedStylesHost_25;
  }
  get _AnimationDriver_26():any {
    if ((this.__AnimationDriver_26 == (null as any))) { (this.__AnimationDriver_26 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_26;
  }
  get _DomRootRenderer_27():import19.DomRootRenderer_ {
    if ((this.__DomRootRenderer_27 == (null as any))) { (this.__DomRootRenderer_27 = new import19.DomRootRenderer_(this._DOCUMENT_21,this._EventManager_24,this._DomSharedStylesHost_25,this._AnimationDriver_26)); }
    return this.__DomRootRenderer_27;
  }
  get _RootRenderer_28():any {
    if ((this.__RootRenderer_28 == (null as any))) { (this.__RootRenderer_28 = import47._createConditionalRootRenderer(this._DomRootRenderer_27,this.parent.get(import47.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_28;
  }
  get _DomSanitizer_29():import20.DomSanitizerImpl {
    if ((this.__DomSanitizer_29 == (null as any))) { (this.__DomSanitizer_29 = new import20.DomSanitizerImpl()); }
    return this.__DomSanitizer_29;
  }
  get _Sanitizer_30():any {
    if ((this.__Sanitizer_30 == (null as any))) { (this.__Sanitizer_30 = this._DomSanitizer_29); }
    return this.__Sanitizer_30;
  }
  get _ViewUtils_31():import21.ViewUtils {
    if ((this.__ViewUtils_31 == (null as any))) { (this.__ViewUtils_31 = new import21.ViewUtils(this._RootRenderer_28,this._APP_ID_20,this._Sanitizer_30)); }
    return this.__ViewUtils_31;
  }
  get _IterableDiffers_32():any {
    if ((this.__IterableDiffers_32 == (null as any))) { (this.__IterableDiffers_32 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_32;
  }
  get _KeyValueDiffers_33():any {
    if ((this.__KeyValueDiffers_33 == (null as any))) { (this.__KeyValueDiffers_33 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_33;
  }
  get _SharedStylesHost_34():any {
    if ((this.__SharedStylesHost_34 == (null as any))) { (this.__SharedStylesHost_34 = this._DomSharedStylesHost_25); }
    return this.__SharedStylesHost_34;
  }
  get _Title_35():import22.Title {
    if ((this.__Title_35 == (null as any))) { (this.__Title_35 = new import22.Title()); }
    return this.__Title_35;
  }
  get _BrowserXhr_36():import23.BrowserXhr {
    if ((this.__BrowserXhr_36 == (null as any))) { (this.__BrowserXhr_36 = new import23.BrowserXhr()); }
    return this.__BrowserXhr_36;
  }
  get _ResponseOptions_37():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_37 == (null as any))) { (this.__ResponseOptions_37 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_37;
  }
  get _XSRFStrategy_38():any {
    if ((this.__XSRFStrategy_38 == (null as any))) { (this.__XSRFStrategy_38 = import6._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_38;
  }
  get _XHRBackend_39():import25.XHRBackend {
    if ((this.__XHRBackend_39 == (null as any))) { (this.__XHRBackend_39 = new import25.XHRBackend(this._BrowserXhr_36,this._ResponseOptions_37,this._XSRFStrategy_38)); }
    return this.__XHRBackend_39;
  }
  get _RequestOptions_40():import26.BaseRequestOptions {
    if ((this.__RequestOptions_40 == (null as any))) { (this.__RequestOptions_40 = new import26.BaseRequestOptions()); }
    return this.__RequestOptions_40;
  }
  get _Http_41():any {
    if ((this.__Http_41 == (null as any))) { (this.__Http_41 = import6.httpFactory(this._XHRBackend_39,this._RequestOptions_40)); }
    return this.__Http_41;
  }
  get _RadioControlRegistry_42():import27.RadioControlRegistry {
    if ((this.__RadioControlRegistry_42 == (null as any))) { (this.__RadioControlRegistry_42 = new import27.RadioControlRegistry()); }
    return this.__RadioControlRegistry_42;
  }
  get _ErrorService_43():import28.ErrorService {
    if ((this.__ErrorService_43 == (null as any))) { (this.__ErrorService_43 = new import28.ErrorService()); }
    return this.__ErrorService_43;
  }
  get _MessageService_44():import29.MessageService {
    if ((this.__MessageService_44 == (null as any))) { (this.__MessageService_44 = new import29.MessageService(this._Http_41,this._ErrorService_43)); }
    return this.__MessageService_44;
  }
  get _FormBuilder_45():import30.FormBuilder {
    if ((this.__FormBuilder_45 == (null as any))) { (this.__FormBuilder_45 = new import30.FormBuilder()); }
    return this.__FormBuilder_45;
  }
  get _ROUTES_46():any[] {
    if ((this.__ROUTES_46 == (null as any))) { (this.__ROUTES_46 = [
      [
        {
          path: '',
          redirectTo: 'signup',
          pathMatch: 'full'
        }
        ,
        {
          path: 'signup',
          component: import48.SignupComponent
        }
        ,
        {
          path: 'signin',
          component: import49.SigninComponent
        }
        ,
        {
          path: 'logout',
          component: import50.LogoutComponent
        }

      ]
      ,
      [
        {
          path: '',
          redirectTo: '/messages',
          pathMatch: 'full'
        }
        ,
        {
          path: 'messages',
          component: import51.MessagesComponent
        }
        ,
        {
          path: 'auth',
          component: import52.AuthenticationComponent,
          loadChildren: './auth/auth.module#AuthModule'
        }

      ]

    ]
    ); }
    return this.__ROUTES_46;
  }
  get _ROUTER_CONFIGURATION_47():any {
    if ((this.__ROUTER_CONFIGURATION_47 == (null as any))) { (this.__ROUTER_CONFIGURATION_47 = {}); }
    return this.__ROUTER_CONFIGURATION_47;
  }
  get _LocationStrategy_48():any {
    if ((this.__LocationStrategy_48 == (null as any))) { (this.__LocationStrategy_48 = import5.provideLocationStrategy(this.parent.get(import53.PlatformLocation),this.parent.get(import54.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_47)); }
    return this.__LocationStrategy_48;
  }
  get _Location_49():import31.Location {
    if ((this.__Location_49 == (null as any))) { (this.__Location_49 = new import31.Location(this._LocationStrategy_48)); }
    return this.__Location_49;
  }
  get _UrlSerializer_50():import32.DefaultUrlSerializer {
    if ((this.__UrlSerializer_50 == (null as any))) { (this.__UrlSerializer_50 = new import32.DefaultUrlSerializer()); }
    return this.__UrlSerializer_50;
  }
  get _RouterOutletMap_51():import33.RouterOutletMap {
    if ((this.__RouterOutletMap_51 == (null as any))) { (this.__RouterOutletMap_51 = new import33.RouterOutletMap()); }
    return this.__RouterOutletMap_51;
  }
  get _NgModuleFactoryLoader_52():import34.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_52 == (null as any))) { (this.__NgModuleFactoryLoader_52 = new import34.SystemJsNgModuleLoader(this._Compiler_19,this.parent.get(import34.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_52;
  }
  get _Router_53():any {
    if ((this.__Router_53 == (null as any))) { (this.__Router_53 = import5.setupRouter(this._ApplicationRef_18,this._UrlSerializer_50,this._RouterOutletMap_51,this._Location_49,this,this._NgModuleFactoryLoader_52,this._Compiler_19,this._ROUTES_46,this._ROUTER_CONFIGURATION_47)); }
    return this.__Router_53;
  }
  get _ActivatedRoute_54():any {
    if ((this.__ActivatedRoute_54 == (null as any))) { (this.__ActivatedRoute_54 = import5.rootRoute(this._Router_53)); }
    return this.__ActivatedRoute_54;
  }
  get _APP_BOOTSTRAP_LISTENER_55():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_55 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_55 = [import5.initialRouterNavigation(this._Router_53,this._ROUTER_CONFIGURATION_47)]); }
    return this.__APP_BOOTSTRAP_LISTENER_55;
  }
  get _AuthService_56():import35.AuthService {
    if ((this.__AuthService_56 == (null as any))) { (this.__AuthService_56 = new import35.AuthService(this._Http_41,this._ErrorService_43)); }
    return this.__AuthService_56;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import55.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._HttpModule_5 = new import6.HttpModule();
    this._InternalFormsSharedModule_6 = new import7.InternalFormsSharedModule();
    this._FormsModule_7 = new import8.FormsModule();
    this._MessageModule_8 = new import9.MessageModule();
    this._ReactiveFormsModule_9 = new import8.ReactiveFormsModule();
    this._AuthModule_10 = new import10.AuthModule();
    this._AppModule_11 = new import1.AppModule();
    this._ErrorHandler_14 = import4.errorHandler();
    this._ApplicationInitStatus_15 = new import12.ApplicationInitStatus(this.parent.get(import12.APP_INITIALIZER,(null as any)));
    this._Testability_16 = new import13.Testability(this.parent.get(import46.NgZone));
    this._ApplicationRef__17 = new import14.ApplicationRef_(this.parent.get(import46.NgZone),this.parent.get(import56.Console),this,this._ErrorHandler_14,this,this._ApplicationInitStatus_15,this.parent.get(import13.TestabilityRegistry,(null as any)),this._Testability_16);
    return this._AppModule_11;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import6.HttpModule)) { return this._HttpModule_5; }
    if ((token === import7.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_6; }
    if ((token === import8.FormsModule)) { return this._FormsModule_7; }
    if ((token === import9.MessageModule)) { return this._MessageModule_8; }
    if ((token === import8.ReactiveFormsModule)) { return this._ReactiveFormsModule_9; }
    if ((token === import10.AuthModule)) { return this._AuthModule_10; }
    if ((token === import1.AppModule)) { return this._AppModule_11; }
    if ((token === import57.LOCALE_ID)) { return this._LOCALE_ID_12; }
    if ((token === import11.NgLocalization)) { return this._NgLocalization_13; }
    if ((token === import58.ErrorHandler)) { return this._ErrorHandler_14; }
    if ((token === import12.ApplicationInitStatus)) { return this._ApplicationInitStatus_15; }
    if ((token === import13.Testability)) { return this._Testability_16; }
    if ((token === import14.ApplicationRef_)) { return this._ApplicationRef__17; }
    if ((token === import14.ApplicationRef)) { return this._ApplicationRef_18; }
    if ((token === import15.Compiler)) { return this._Compiler_19; }
    if ((token === import43.APP_ID)) { return this._APP_ID_20; }
    if ((token === import59.DOCUMENT)) { return this._DOCUMENT_21; }
    if ((token === import16.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_22; }
    if ((token === import17.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_23; }
    if ((token === import17.EventManager)) { return this._EventManager_24; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_25; }
    if ((token === import60.AnimationDriver)) { return this._AnimationDriver_26; }
    if ((token === import19.DomRootRenderer)) { return this._DomRootRenderer_27; }
    if ((token === import61.RootRenderer)) { return this._RootRenderer_28; }
    if ((token === import20.DomSanitizer)) { return this._DomSanitizer_29; }
    if ((token === import62.Sanitizer)) { return this._Sanitizer_30; }
    if ((token === import21.ViewUtils)) { return this._ViewUtils_31; }
    if ((token === import63.IterableDiffers)) { return this._IterableDiffers_32; }
    if ((token === import64.KeyValueDiffers)) { return this._KeyValueDiffers_33; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_34; }
    if ((token === import22.Title)) { return this._Title_35; }
    if ((token === import23.BrowserXhr)) { return this._BrowserXhr_36; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_37; }
    if ((token === import65.XSRFStrategy)) { return this._XSRFStrategy_38; }
    if ((token === import25.XHRBackend)) { return this._XHRBackend_39; }
    if ((token === import26.RequestOptions)) { return this._RequestOptions_40; }
    if ((token === import66.Http)) { return this._Http_41; }
    if ((token === import27.RadioControlRegistry)) { return this._RadioControlRegistry_42; }
    if ((token === import28.ErrorService)) { return this._ErrorService_43; }
    if ((token === import29.MessageService)) { return this._MessageService_44; }
    if ((token === import30.FormBuilder)) { return this._FormBuilder_45; }
    if ((token === import67.ROUTES)) { return this._ROUTES_46; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_47; }
    if ((token === import54.LocationStrategy)) { return this._LocationStrategy_48; }
    if ((token === import31.Location)) { return this._Location_49; }
    if ((token === import32.UrlSerializer)) { return this._UrlSerializer_50; }
    if ((token === import33.RouterOutletMap)) { return this._RouterOutletMap_51; }
    if ((token === import68.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_52; }
    if ((token === import55.Router)) { return this._Router_53; }
    if ((token === import69.ActivatedRoute)) { return this._ActivatedRoute_54; }
    if ((token === import43.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_55; }
    if ((token === import35.AuthService)) { return this._AuthService_56; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__17.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);